# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and release

on:
  push:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  write-all

jobs:
  Build-Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run:  |
        ./Setup.ps1 && msbuild TetherInstaller.sln /p:Configuration=Release /p:Platform=x64 /p:CI_BUILD=${{ github.run_number }}
    - name: upload artifact
      uses: actions/upload-artifact@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        path: ${{ github.workspace }}/x64/Release/TetherSetup.exe
        name: Tether-Setup-${{ github.run_number }}

    - name: Remove Zip
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        rm Release/TetherInstaller.zip

    - name: upload artifact
      uses: actions/upload-artifact@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        path: ${{ github.workspace }}/Release
        name: Tether-Windows-Build-${{ github.run_number }}

  Build-Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libsdl2-dev
    - name: build
      run: |
          cmake -S . -B Build/ -DTETHER_CI=${{ github.run_number }}
          cd Build/
          cmake --build .
    - name: make-release
      run: |
          ls -R
          mkdir Release
          cp -rf NorthstarInstaller/Data Release/Data
          cp LICENSE.txt Release/License.txt
          cp Build/TetherInstaller Release/TetherInstaller
    - name: upload artifact
      uses: actions/upload-artifact@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        path: Release
        name: Tether-Linux-Build-${{ github.run_number }}

  Release:
    runs-on: ubuntu-latest
    needs: [Build-Windows, Build-Linux]
    steps:
    - name: Retrieve Release Artifacts
      uses: actions/download-artifact@v2
      with:
        path: Release

    - name: "zip artifacts"
      run: |
        cd ${{ github.workspace }}/Release/Tether-Windows-Build-${{ github.run_number }}
        zip -r ${{ github.workspace }}/tether-win.zip ./*
        cd ${{ github.workspace }}/Release/
        tar -czf ${{ github.workspace }}/tether_linux.tar.gz Tether-Linux-Build-${{ github.run_number }}
    - name: list-directory
      run: "ls -R"

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: "Build #${{ github.run_number }}"
        tag_name: Build-${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: tether_linux.tar.gz
        asset_name: Tether-Linux-Build-${{ github.run_number }}.tar.gz
        asset_content_type: application/gzip

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: tether-win.zip
        asset_name: Tether-Windows-Build-${{ github.run_number }}.zip
        asset_content_type: application/zip
    - name: upload windows installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}Release/Tether-Setup-${{ github.run_number }}/TetherSetup.exe
        asset_name: Tether-Win-Setup.exe
        asset_content_type: application/octet-stream